version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mybooks-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: sm@rt
      MYSQL_DATABASE: mybooks_db
    volumes:
      - db_data:/var/lib/mysql
      - ./php/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - mybooks-network

  web:
    build: 
      context: ./php
      dockerfile: Dockerfile
    container_name: mybooks-webapp
    restart: always
    depends_on:
      - db
    #volumes:
   #   - ./php:/var/www/html
    ports:
      - "8084:80"
    networks:
      - mybooks-network

networks:
  mybooks-network:

volumes:
  db_data:
